// <auto-generated />
using System;
using Assignment4Games.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment4Games.Migrations
{
    [DbContext(typeof(Assignment4GamesContext))]
    [Migration("20190411193907_addedPaymentToDB")]
    partial class addedPaymentToDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment4Games.Models.Game", b =>
                {
                    b.Property<string>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Developer");

                    b.Property<string>("GameName");

                    b.Property<string>("Genre");

                    b.Property<string>("Languages");

                    b.Property<string>("Platform");

                    b.Property<int>("Rating");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Assignment4Games.Models.Payment", b =>
                {
                    b.Property<int>("prestono")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int>("CVV");

                    b.Property<int>("Card");

                    b.Property<int>("Date");

                    b.Property<int>("Pass");

                    b.Property<string>("age")
                        .IsRequired();

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("mobile")
                        .IsRequired();

                    b.Property<string>("name")
                        .IsRequired();

                    b.HasKey("prestono");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Assignment4Games.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<string>("GameId");

                    b.Property<DateTime>("Time");

                    b.Property<string>("UserName");

                    b.HasKey("ReviewId");

                    b.ToTable("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
